version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: music-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://db:27017
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: music-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - backend

  db:
    image: mongo
    container_name: music-db
    ports:
      - "27017:27017"
    volumes:
      - music-db-data:/data/db

volumes:
  music-db-data:
